forklift/urls.py
#INCLUDE GENERIC
from django.urls import path, include

#IMPORT FORKLIFTS
from .views import forklift_index, forklift_view, forklift_edit, forklift_add

#IMPORT VIEWS PROVIDERS
from .views import forklift_service_providers, forklift_service_providers_view, forklift_service_providers_add, forklift_service_providers_edit

#IMPORT VIEWS HOLDERS
from .views import forklift_holders, forklift_holders_view, forklift_holders_edit, forklift_holders_add

#IMPORT VIEW BRANDS
from .views import forklift_brands, forklift_brands_view, forklift_brands_edit, forklift_brands_add

#IMPORT VIEWS STATUS
from .views import forklift_status, forklift_status_view, forklift_status_edit, forklift_status_add

#IMPORT VIEWS LOTO
from .views import forklift_loto, forklift_loto_view, forklift_loto_add, forklift_loto_delete

#IMPORT VIEWS LOTO LOG
from .views import forklift_loto_log, forklift_loto_log_view, forklift_loto_log_add

#IMPORT VIEWS INSPECTION SHEET
from .views import inspection_sheet_language, inspection_sheet_form_es, inspection_sheet_form_en, inspection, inspection_log, inspection_view, inspection_release

#IMPORT VIEWS WATER TRAYCING
from .views import water_track_add, water_track

urlpatterns = [

#URL EXTRA (JSON) PATTERNS
    path('json/', include('forklift.json')),

#URL INDEX (FORKLIFTS)
    path('', forklift_index, name='forklift_index_view'),
    path('view/<int:id>/', forklift_view, name='forklift_view'),
    path('edit/<int:id>/', forklift_edit, name='forklift_edit'),
    path('add/', forklift_add, name='forklift_add'),

#WATER TRAYCING
    path('water/', water_track, name='water_track'),
    path('water/add/<int:id>/', water_track_add, name='water_track_add'),

#SERVICEPROVIDERS
    path('service/providers/', forklift_service_providers, name='forklift_service_providers'),
    path('service/providers/view/<int:id>/', forklift_service_providers_view, name='forklift_service_providers_view'),
    path('service/providers/edit/<int:id>/', forklift_service_providers_edit, name='forklift_service_providers_edit'),
    path('service/providers/add/', forklift_service_providers_add, name='forklift_service_providers_add'),

#HOLDERS
    path('holders/', forklift_holders, name='forklift_holders'),
    path('holders/view/<int:id>/', forklift_holders_view, name='forklift_holders_view'),
    path('holders/edit/<int:id>/', forklift_holders_edit, name='forklift_holders_edit'),
    path('holders/add/', forklift_holders_add, name='forklift_holders_add'),

#BRANDS
    path('brands/', forklift_brands, name='forklift_brands'),
    path('brands/view/<int:id>/', forklift_brands_view, name='forklift_brands_view'),
    path('brands/edit/<int:id>/', forklift_brands_edit, name='forklift_brands_edit'),
    path('brands/add/', forklift_brands_add, name='forklift_brands_add'),

#STATUS
    path('status/', forklift_status, name='forklift_status'),
    path('status/view/<int:id>/', forklift_status_view, name='forklift_status_view'),
    path('status/edit/<int:id>/', forklift_status_edit, name='forklift_status_edit'),
    path('status/add/', forklift_status_add, name='forklift_status_add'),

#LOTO
    path('loto/', forklift_loto, name='forklift_loto'),
    path('loto/view/<int:id>/', forklift_loto_view, name='forklift_loto_view'),
    path('loto/add/<int:id>/', forklift_loto_add, name='forklift_loto_add'),
    path('loto/delete/<int:id>/', forklift_loto_delete, name='forklift_loto_delete'),
#LOTO LOG
    path('loto/log/', forklift_loto_log, name='forklift_loto_log'),
    path('loto/log/view/<int:id>/', forklift_loto_log_view, name='forklift_loto_log_view'),
    path('loto/log/add/<int:id>', forklift_loto_log_add, name='forklift_loto_log_add'),

#INSPECTION SHEET
    path('inspection/', inspection, name='inspection'),
    path('inspection/log/', inspection_log, name='inspection_log'),
    path('inspection/view/<int:id>/', inspection_view, name='inspection_view'),
    path('inspection/release/<int:id>/', inspection_release, name='inspection_release'),
    path('drivers/', inspection_sheet_language, name='inspection_sheet_language'),
    path('drivers/es/', inspection_sheet_form_es, name='inspection_sheet_form_es'),
    path('drivers/en/', inspection_sheet_form_en, name='inspection_sheet_form_en'),
]

staff/urls.py
#IMPORT DJANGO FUNCTIONS
from django.urls import path
from django.contrib import admin

#IMPORT VIEWS FOR STAFF SECTTION
from .views import staff_index, staff_view, staff_add, staff_edit, staff_password_edit, staff_json_response, staff_json_delete

#URLS PATTERNS START HERE
urlpatterns = [

#URL SECTION FOR STAFF
    #INDEX
        path('', staff_index, name='staff_index'),

        path('view/<int:id>/', staff_view, name='staff_view'),

        path('add/', staff_add, name='staff_add'),

        path('edit/<int:id>/', staff_edit, name='staff_edit'),
    #JSON DB RESPONSE
        path('json/pull/', staff_json_response, name='staff_json_response'),
    #DELETE
        path('json/delete/<int:id>/', staff_json_delete, name='staff_json_delete'),
    #EDIT PASSWORD
        path('password/edit/<int:id>/', staff_password_edit, name='staff_password_edit'),
    #EDIT GENERAL
        path('edit/<int:id>/', staff_edit, name='staff_edit'),
]

suiplu/urls.py
#IMPORT GENERIC 
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin

#IMPORT LOGIN AND LOGOUT VIEW
from autenticacion.views import logout_view, login_view

#IMPORT LOGIN AND LOGOUT VIEW
from autenticacion.views import ins_logout_view, ins_login_view

#IMPORT INDEX VIEWS
from .views import index

#IMPORT EQUIPMENT VIEWS
from .views import equipment_index, equipment_view, equipment_request_json, equipment_imagen_upload_view, equipment_delete

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    #URLS FOR LOGIN AND LOGOUT
    path('logout/', logout_view, name='logout_view'),
    path('login/', login_view, name='login_view'),

    #URLS FOR LOGIN AND LOGOUT ( FORKLIFT DRIVERS)
    path('drivers/logout/', ins_logout_view, name='ins_logout_view'),
    path('drivers/login/', ins_login_view, name='ins_login_view'),

    #URL FOR DJANGO ADMIN
    path('administracion/', admin.site.urls),

    #URL FOR CONFIGURACION APP
    path('equipment/', include('equipment.urls')),

    #URL FOR FORKLIFTS APP
    path('forklifts/', include('forklift.urls')),

    #URL FOR LADDERS APP
    path('ladders/', include('ladders.urls')),

    #URL FOR SCALES APP
    path('scales/', include('scales.urls')),

    #URL FOR INVENTORY APP
    path('inventory/', include('inventory.urls')),

    #URL FOR STORAGE APP
    path('storage/', include('storage.urls')),

    #URL FOR STAFF APP
    path('staff/', include('staff.urls')),

    #URL FOR INDEX
    path('', index, name='index'),

]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forklift/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

#FORKLIFT PROPERY
class ForkliftOwners(models.Model):
	id = models.AutoField(primary_key=True)
	name = models.CharField(max_length=255)
	phone_number = models.CharField(max_length=25)
	service_description = models.TextField()
	contact_person = models.CharField(max_length=100)
	address = models.TextField()
	website = models.URLField(blank=True, null=True)
	email = models.EmailField()
	imagen = models.ImageField(upload_to='forklifts/holders/banners/', null=True)
	def __str__(self):
		return self.name


#FORKLIFT SERVICE PROVIDERS
class ForkliftServiceProviders(models.Model):
	id = models.AutoField(primary_key=True)
	name = models.CharField(max_length=255)
	phone_number = models.CharField(max_length=25)
	service_description = models.TextField()
	contact_person = models.CharField(max_length=100)
	address = models.TextField()
	website = models.URLField(blank=True, null=True)
	email = models.EmailField()
	imagen = models.ImageField(upload_to='forklifts/serviceproviders/banners/', null=True)
	def __str__(self):
		return self.name


#FORKLIFT BRANDS
class ForkliftBrands(models.Model):
	id = models.AutoField(primary_key=True)
	name = models.CharField(max_length=255)
	color = models.CharField(max_length=255)
	imagen = models.ImageField(upload_to='forklifts/brands/banners/', null=True)
	def __str__(self):
		return self.name



#FORKLIFT STATUS
class ForkliftStatus(models.Model):
	id = models.AutoField(primary_key=True)
	name = models.CharField(max_length=255)
	color = models.CharField(max_length=255)
	def __str__(self):
		return self.name


#FORKLIFT DB MODEL
class Forklifts(models.Model):
	id = models.AutoField(primary_key=True)
	imagen = models.ImageField(upload_to='forklifts/equipment/')
	service_provider =  models.ManyToManyField(ForkliftServiceProviders, blank=True, null=True)
	clave = models.CharField(max_length=255)
	brand = models.ForeignKey(ForkliftBrands, on_delete=models.CASCADE)
	status = models.ForeignKey(ForkliftStatus,on_delete=models.PROTECT, default=1)
	modelo =  models.CharField(max_length=255)
	serial =  models.CharField(max_length=255)
	owner = models.ForeignKey(ForkliftOwners, on_delete=models.CASCADE)
	powered_opt = [
        ("G", "LPG"),
        ("E", "Electric"),
    ]
	powered = models.CharField(max_length=1, choices=powered_opt)
	last_batery = models.DateTimeField(default=timezone.now)
	batery_target= models.IntegerField()
	def __str__(self):
		return str(self.clave) +  str(" / ") + self.brand.name + str(" / ") + self.modelo + str(" / ") + self.serial


#FORKLIFT LOTO
class WaterEntry(models.Model):
	id = models.AutoField(primary_key=True)
	forklift = models.ForeignKey(Forklifts, on_delete=models.CASCADE)
	fecha = models.DateTimeField(default=timezone.now)
	usuario = models.ForeignKey(User, on_delete=models.SET_DEFAULT, default="1")


#FORKLIFT LOTO
class InitialLoto(models.Model):
	id = models.AutoField(primary_key=True)
	forklift = models.ForeignKey(Forklifts, on_delete=models.CASCADE)
	start = models.DateTimeField(default=timezone.now)
	reason = models.CharField(max_length=100)
	description = models.TextField()
	startusuario = models.ForeignKey(User, on_delete=models.SET_DEFAULT, default="1")


#FORKLIFT LOTO
class Loto(models.Model):
	id = models.AutoField(primary_key=True)
	forklift = models.ForeignKey(Forklifts, on_delete=models.CASCADE)
	start = models.DateTimeField(default=timezone.now)
	end = models.DateTimeField(default=timezone.now)
	reason = models.CharField(max_length=100)
	description = models.TextField()
	startusuario = models.ForeignKey(User, on_delete=models.SET_DEFAULT, default="1")
	endusuario = models.ForeignKey(User, on_delete=models.SET_DEFAULT, default="1", related_name='end_lotos')

#FORKLIFT INSPECTION
class ForkliftInspection(models.Model):
	id = models.AutoField(primary_key=True)
	forklift = models.ForeignKey(Forklifts, on_delete=models.CASCADE)
	usuario = models.ForeignKey(User, on_delete=models.CASCADE)
	fecha = models.DateTimeField(default=timezone.now)
	check1 = models.BooleanField()
	check2 = models.BooleanField()
	check3 = models.BooleanField()
	check4 = models.BooleanField()
	check5 = models.BooleanField()
	check6 = models.BooleanField()
	check7 = models.BooleanField()
	check8 = models.BooleanField()
	check9 = models.BooleanField()
	check10 = models.BooleanField()
	check11 = models.BooleanField()
	check12 = models.BooleanField()
	des1 = models.TextField(null=True,blank=True)
	des2 = models.TextField(null=True,blank=True)
	des3 = models.TextField(null=True,blank=True)
	des4 = models.TextField(null=True,blank=True)
	des5 = models.TextField(null=True,blank=True)
	des6 = models.TextField(null=True,blank=True)
	des7 = models.TextField(null=True,blank=True)
	des8 = models.TextField(null=True,blank=True)
	des9 = models.TextField(null=True,blank=True)
	des10 = models.TextField(null=True,blank=True)
	des11 = models.TextField(null=True,blank=True)
	des12 = models.TextField(null=True,blank=True)
	valid = models.BooleanField()

templates/forklifts/brands/add.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    SuipluMX - Adding new forklift brand
{% endblock %}

{% block content %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Forklifts</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            {% include "forklifts/fork_toolbar.html" %}
        </div>
    </div>
    <h5>Adding new forklift brand</h5>
    <div class="row p-2 mb-0">
        <div class="containervieweqipment">
            <div class="containervieweqipmenthead">
                <div class="row">
                    <div class="col-6">General information:</div>
                    <div class="col-6">
                        <div class="text-end">
                        </div>
                    </div>
                </div>
            </div>
            <div class="containervieweqipmentbody">
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div class="pb-2 text-end">
                        <button type="submit" class="btn btn-success">Add</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script src="{% static 'js/forklifts/forklifts.js' %}"></script>
{% endblock %}

templates/forklifts/brands/edit.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    SuipluMX - Editing {{data.name}}
{% endblock %}

{% block content %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Forklifts</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            {% include "forklifts/fork_toolbar.html" %}
        </div>
    </div>
    <h5>Editing forklift brand: {{data.name}}</h5>
{{form.errors}}
    <div class="row p-2 mb-0">
        <div class="containervieweqipment">
            <div class="containervieweqipmenthead">
                <div class="row">
                    <div class="col-6">General information:</div>
                    <div class="col-6">
                        <div class="text-end">
                        </div>
                    </div>
                </div>
            </div>
            <div class="containervieweqipmentbody">
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{form.as_p}}
                    <div class="pb-2 text-end">
                        <button type="submit" class="btn btn-success">Update</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script src="{% static 'js/forklifts/forklifts.js' %}"></script>
{% endblock %}

templates/forklifts/brands/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}SuipluMX - Registrated forklift brands{% endblock %}
{% block content %}
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Forklifts</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            {% include "forklifts/fork_toolbar.html" %}
        </div>
      </div>
<div class="row pb-2 px-1">
  <div class="col-6"><h5>Registrated forklift brands</h5></div>
  <div class="col-6">
      {% if perms.forklift.add_forkliftbrands %}
          <div class="text-end"><a href="{% url 'forklift_brands_add' %}" class="btn btn-dark"><img class="filter-white" src="{% static 'images/ico/card-heading.svg' %}" /> Add brand</a></div>
      {% else %}
      {% endif %}
  </div>
</div>
<table id="datatable-contenido" class="pt-2 table table-striped table-hover">
    <thead>
        <tr>
            <th>Banner</th>
            <th>Brand</th>
            <th class="text-end">Operations</th>
        </tr>
    </thead>
    <tbody id="tableContenido_results"></tbody>
</table>
<script src="{% static 'js/forklifts/brands.js' %}"></script>
<script src="{% static 'js/forklifts/complex_brands.js' %}"></script>
{% endblock %}

templates/forklifts/brands/view.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    SuipluMX - Viewing {{data.name}}
{% endblock %}

{% block content %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Forklifts</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            {% include "forklifts/fork_toolbar.html" %}
        </div>
    </div>
    <h5>Viewing forklift brand: {{data.name}}</h5>
    <div class="text-end"></div>
    <script src="{% static 'js/functions_forklifts.js' %}"></script>
    <div class="row">
        <div class="col-4 p-2 mb-0">
            <div class="containervieweqipment">
                <div class="containervieweqipmenthead">
                    <div class="row">
                        <div class="col-6">Banner</div>
                        <div class="col-6">
                            <div class="text-end">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="align-middle text-center containervieweqipmentbody">
                    <img class="img_holder" src="/media/{{ data.imagen }}">
                </div>
            </div>
        </div>

        <div class="col-8 p-2">
            <div class="containervieweqipment">
                <div class="containervieweqipmenthead">
                    <div class="row">
                        <div class="col-6">General information</div>
                        <div class="col-6">
                            <div class="text-end">
                                {% if perms.forklift.change_forkliftbrands %}
                                <div class="text-end">
                                    <a href="{% url 'forklift_brands_edit' data.id %}" name="edit_b" id="edit_b" class="nav-link"><span class="align-text-bottom"><img class="filter-white" src="{% static 'images/ico/pencil-square.svg' %}"></span></a>
                                </div>
                                {% else %}
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="containervieweqipmentbody">
                    <div class="row">
                        <div class="col-3 fw-bolder">Company's name:</div>
                        <div class="col-9 fw-medium">{{ data.name }}</div>
                    </div>
                    <div class="row">
                        <div class="col-3 fw-bolder">Color: </div>
                        <div class="col-9 fw-medium"><span style="height: 18px;width: 18px;background-color:{{ data.color  }};border-radius: 50%;vertical-align: sub;display: inline-block;" class="dot"></span> {{ data.color }}</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% if perms.forklift.delete_forkliftbrands %}
    <div class="row p-2 mb-0">
            <div class="containerdanger">
                <div class="containerdangerhead">
                    <div class="row">
                        <div class="col-6"><a class="fw-bolder text-reset text-decoration-none">Danger zone</a></div>
                        <div class="col-6">
                            <div class="text-end">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="containerdangerbody">
                    <hr>
                    <div class="row">
                        <div class="col-9 align-middle">
                            <a  class="fw-bolder text-reset text-decoration-none">Delete this brand</a><br>
                            <a class="fw-medium text-reset text-decoration-none">Once you delete this brand, there is no going back. Please be certain.</a>
                        </div>
                        <div class="col-3 text-end"> <button type="button" onClick='delete_content({{data.id}})' class="btn btn-danger">Delete this brand</button></div>
                    </div>
                    <hr>
                </div>
            </div>
    </div>
    {% else %}
    {% endif %}
    <script src="{% static 'js/forklifts/brands.js' %}"></script>
    <!-- MODAL DELETE -->
  <div class="modal fade" id="modal_delete" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="staticBackdropLabel">Are you sure you want to delete this brand?</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">All related items will be deleted. You can't undo this action.
          <form class="eliminar-formulario" method="post" action="{% url 'api_del_forklifts_brands' data.id %}">
            {% csrf_token %}
            <input type="hidden" name="delete_id" id="delete_id" value="{{data.id}}">
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-dark" data-bs-dismiss="modal">Cancel</button>
          <button type="submit" class="btn btn-danger">Delete</button>
        </div>
          </form>
      </div>
    </div>
  </div>
{% endblock %}