ladders/urls.py
#INCLUDE
from django.urls import path, include

#INCLUDE LADDERS APP VIEWS
#IMPORT MAIN INDEX
from .views import ladders_index, ladders_index_json, ladders_view, ladders_add, ladders_delete, ladders_edit
#IMPORT MATERIALS
from .views import ladders_materials, ladders_materials_json, ladders_materials_add, ladders_materials_view, ladders_materials_edit, ladders_materials_delete
#IMPORT STATUS
from .views import ladders_status, ladders_status_add, ladders_status_view, ladders_status_delete, ladders_status_edit
#IMPORT INSPECTION
from .views import ladders_inspection, ladders_inspection_add
#IMPORT BRANDS
from .views import ladders_brands, ladders_brands_json, ladders_brands_view, ladders_brands_edit, ladders_brands_add, ladders_brands_delete

urlpatterns = [
    #URL PATTERN INDEX
    path('', ladders_index, name='ladders_index_view'),
    path('view/<int:id>/', ladders_view, name='ladders_view'),
    path('edit/<int:id>/', ladders_edit, name='ladders_edit'),
    path('add/', ladders_add, name='ladders_add'),
    path('delete/<int:id>', ladders_delete, name='ladders_delete'),
    path('json/pull/', ladders_index_json, name='ladders_index_view_json'),

    #URL PATTERN BRANDS
    path('brands/', ladders_brands, name='ladders_brands'),
    path('brands/view/<int:id>/', ladders_brands_view, name='ladders_brands_view'),
    path('brands/edit/<int:id>/', ladders_brands_edit, name='ladders_brands_edit'),
    path('brands/add/', ladders_brands_add, name='ladders_brands_add'),
    path('brands/delete/<int:id>/', ladders_brands_delete, name='ladders_brands_delete'),
    path('json/pull/brands/', ladders_brands_json, name='ladders_brands_json'),

    #URL PATTERN MATERIALS
    path('materials/', ladders_materials, name='ladders_materials'),
    path('materials/add/', ladders_materials_add, name='ladders_materials_add'),
    path('materials/view/<int:id>/', ladders_materials_view, name='ladders_materials_view'),
    path('materials/edit/<int:id>/', ladders_materials_edit, name='ladders_materials_edit'),
    path('materials/delete/<int:id>/', ladders_materials_delete, name='ladders_materials_delete'),
    path('json/pull/materials/', ladders_materials_json, name='ladders_materials_json'),

    #URL PATTERN STATUS
    path('status/', ladders_status, name='ladders_status'),
    path('status/add/', ladders_status_add, name='ladders_status_add'),
    path('status/view/<int:id>/', ladders_status_view, name='ladders_status_view'),
    path('status/edit/<int:id>/', ladders_status_edit, name='ladders_status_edit'),
    path('status/delete/<int:id>/', ladders_status_delete, name='ladders_status_delete'),

    #URL PATTERN INSPECTION
    path('inspection/', ladders_inspection, name='ladders_inspection'),
    path('inspection/add/<int:id>/', ladders_inspection_add, name='ladders_inspection_add'),

]

staff/urls.py
#IMPORT DJANGO FUNCTIONS
from django.urls import path
from django.contrib import admin

#IMPORT VIEWS FOR STAFF SECTTION
from .views import staff_index, staff_view, staff_add, staff_edit, staff_password_edit, staff_json_response, staff_json_delete

#URLS PATTERNS START HERE
urlpatterns = [

#URL SECTION FOR STAFF
    #INDEX
        path('', staff_index, name='staff_index'),

        path('view/<int:id>/', staff_view, name='staff_view'),

        path('add/', staff_add, name='staff_add'),

        path('edit/<int:id>/', staff_edit, name='staff_edit'),
    #JSON DB RESPONSE
        path('json/pull/', staff_json_response, name='staff_json_response'),
    #DELETE
        path('json/delete/<int:id>/', staff_json_delete, name='staff_json_delete'),
    #EDIT PASSWORD
        path('password/edit/<int:id>/', staff_password_edit, name='staff_password_edit'),
    #EDIT GENERAL
        path('edit/<int:id>/', staff_edit, name='staff_edit'),
]

suiplu/urls.py
#IMPORT GENERIC 
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin

#IMPORT LOGIN AND LOGOUT VIEW
from autenticacion.views import logout_view, login_view

#IMPORT LOGIN AND LOGOUT VIEW
from autenticacion.views import ins_logout_view, ins_login_view

#IMPORT INDEX VIEWS
from .views import index

#IMPORT EQUIPMENT VIEWS
from .views import equipment_index, equipment_view, equipment_request_json, equipment_imagen_upload_view, equipment_delete

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    #URLS FOR LOGIN AND LOGOUT
    path('logout/', logout_view, name='logout_view'),
    path('login/', login_view, name='login_view'),

    #URLS FOR LOGIN AND LOGOUT ( FORKLIFT DRIVERS)
    path('drivers/logout/', ins_logout_view, name='ins_logout_view'),
    path('drivers/login/', ins_login_view, name='ins_login_view'),

    #URL FOR DJANGO ADMIN
    path('administracion/', admin.site.urls),

    #URL FOR CONFIGURACION APP
    path('equipment/', include('equipment.urls')),

    #URL FOR FORKLIFTS APP
    path('forklifts/', include('forklift.urls')),

    #URL FOR LADDERS APP
    path('ladders/', include('ladders.urls')),

    #URL FOR SCALES APP
    path('scales/', include('scales.urls')),

    #URL FOR INVENTORY APP
    path('inventory/', include('inventory.urls')),

    #URL FOR STORAGE APP
    path('storage/', include('storage.urls')),

    #URL FOR STAFF APP
    path('staff/', include('staff.urls')),

    #URL FOR INDEX
    path('', index, name='index'),

]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ladders/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date, datetime, timedelta, timezone
from django.utils import timezone
from storage.models import Locations
#LADDERS BRANDS
class LattersBrands(models.Model):
	id = models.AutoField(primary_key=True)
	name = models.CharField(max_length=255)
	color = models.CharField(max_length=255)
	imagen = models.ImageField(upload_to='ladders/brands/banners/', null=True)
	def __str__(self):
		return self.name

#LADDERS MATERIALS
class LattersMaterials(models.Model):
	id = models.AutoField(primary_key=True)
	name = models.CharField(max_length=255)
	color = models.CharField(max_length=255)
	def __str__(self):
		return self.name

#LADDERS STATUS
class LattersStatus(models.Model):
	id = models.AutoField(primary_key=True)
	name = models.CharField(max_length=255)
	color = models.CharField(max_length=255)
	def __str__(self):
		return self.name

#LADDERS DB MODEL
class Ladders(models.Model):
	id = models.AutoField(primary_key=True)
	imagen = models.ImageField(upload_to='ladders/images/')
	clave = models.CharField(max_length=255)
	brand = models.ForeignKey(LattersBrands, on_delete=models.CASCADE)
	modelo =  models.CharField(max_length=255)
	agregado = models.DateTimeField(default=timezone.now)
	material = models.ForeignKey(LattersMaterials, on_delete=models.CASCADE)
	pasos = models.IntegerField()
	status = models.ForeignKey(LattersStatus, on_delete=models.CASCADE)
	location = models.ForeignKey(Locations, on_delete=models.PROTECT)
	def __str__(self):
		return str(self.clave) +  str(" / ") + str(self.brand) +  str(" / ") + str(self.modelo)

class LadderInspectionEntry(models.Model):
	id = models.AutoField(primary_key=True)
	ladder = models.ForeignKey(Ladders, on_delete=models.CASCADE)
	fecha = models.DateTimeField(default=timezone.now)
	usuario = models.ForeignKey(User, on_delete=models.SET_DEFAULT, default="1")
	@staticmethod
	def ha_sido_inspeccionado_este_mes(objeto_id):
		inicio_mes = timezone.now().replace(day=1, hour=0, minute=0, second=0, microsecond=0)
        # Corrección aquí: Uso correcto de timedelta para calcular el fin del mes
		fin_mes = inicio_mes + timedelta(days=31)  # Añade 31 días al inicio del mes
		fin_mes = fin_mes.replace(day=1) - timedelta(seconds=1)  # Retrocede al último momento del mes anterior
		return LadderInspectionEntry.objects.filter(ladder_id=objeto_id, fecha__range=(inicio_mes, fin_mes)).exists()
	def ha_sido_inspeccionado_el_mes_anterior(objeto_id):
		hoy = timezone.now()
        # Primer día del mes actual
		primer_dia_mes_actual = hoy.replace(day=1, hour=0, minute=0, second=0, microsecond=0)
        # Último día del mes anterior (un segundo antes del primer día del mes actual)
		fin_mes_anterior = primer_dia_mes_actual - timedelta(seconds=1)
        # Primer día del mes anterior
		inicio_mes_anterior = fin_mes_anterior.replace(day=1, hour=0, minute=0, second=0, microsecond=0)

		return LadderInspectionEntry.objects.filter(
            ladder_id=objeto_id, 
            fecha__range=(inicio_mes_anterior, fin_mes_anterior)
        ).exists()
	def ha_sido_inspeccionado_dos_meses_atras(objeto_id):
		hoy = timezone.now()
        # Primer día del mes actual
		primer_dia_mes_actual = hoy.replace(day=1, hour=0, minute=0, second=0, microsecond=0)
        # Último día del mes anterior al anterior (un segundo antes del primer día del mes anterior)
		fin_mes_anterior_al_anterior = primer_dia_mes_actual.replace(day=1) - timedelta(days=1)
		fin_mes_anterior_al_anterior = fin_mes_anterior_al_anterior.replace(day=1) - timedelta(seconds=1)
        # Primer día del mes anterior al anterior
		inicio_mes_anterior_al_anterior = fin_mes_anterior_al_anterior.replace(day=1, hour=0, minute=0, second=0, microsecond=0)

		return LadderInspectionEntry.objects.filter(
            ladder_id=objeto_id, 
            fecha__range=(inicio_mes_anterior_al_anterior, fin_mes_anterior_al_anterior)
        ).exists()

ladders/forms.py
import random
from django import forms

from django.contrib.auth.models import User

from .models import LattersStatus, LattersMaterials, LattersBrands, Ladders, LadderInspectionEntry

#DEF COLOR GEN FUNCTION
def color():
    color = "%03x" % random.randint(0, 0xFFF)
    return color

#DEF TAG PLACEHOLDER NUMBER FUNCTION
def tag():
    tag = random.randint(0, 0xFFF)
    return tag

class CreateLadderStatus(forms.ModelForm):
    class Meta:
        model = LattersStatus
        fields = '__all__'
        widgets={
            "name":forms.TextInput(attrs={'placeholder':'Name of the new ladder status'}),
            "color":forms.TextInput(attrs={'data-jscolor="{}"': '', 'value': color}),
        }
        labels = {
            "name": "Name of the status",
        }

class CreateLadderMaterials(forms.ModelForm):
    class Meta:
        model = LattersMaterials
        fields = '__all__'
        widgets={
            "name":forms.TextInput(attrs={'placeholder':'Name of the new ladder material'}),
            "color":forms.TextInput(attrs={'data-jscolor="{}"': '', 'value': color}),
        }
        labels = {
            "name": "Name of the material",
        }
class CreateLadderBrands(forms.ModelForm):
    class Meta:
        model = LattersBrands
        fields = '__all__'
        widgets={
            "name":forms.TextInput(attrs={'class':'form-control form-control-sm','placeholder':'Name of the new ladder brand'}),
            "color":forms.TextInput(attrs={'class':'form-control', 'data-jscolor="{}"': '', 'value': color }),
        }
        labels = {
            "name": "Name of the brand",
        }
class CreateLadderForm(forms.ModelForm):
    class Meta:
        model = Ladders
        fields = ['clave', 'brand', 'modelo', 'material', 'pasos', 'status', 'imagen','location']
        widgets = {
            "clave": forms.TextInput(attrs={'class': 'form-control form-control-sm', 'placeholder': 'Enter Clave'}),
            "brand": forms.Select(attrs={'class': 'form-control form-control-sm'}),
            "modelo": forms.TextInput(attrs={'class': 'form-control form-control-sm', 'placeholder': 'Enter Model'}),
            "material": forms.Select(attrs={'class': 'form-control form-control-sm'}),
            "pasos": forms.TextInput(attrs={'class': 'form-control form-control-sm', 'placeholder': 'Enter # of steps'}),
            "status": forms.Select(attrs={'class': 'form-control form-control-sm'}),
            "location": forms.Select(attrs={'class': 'form-control form-control-sm'}),

        }
        labels = {
            "clave": "Identification tag",
            "modelo": "Model",
            "location": "Location"
        }
class LadderInspectionForm(forms.ModelForm):
    class Meta:
        model = LadderInspectionEntry
        fields = ['usuario','ladder']
        widgets={
            "ladder":forms.Select(attrs={'class':'form-control form-control-sm'}),
            "usuario":forms.Select(attrs={'class':'form-control form-control-sm'}),
        }
    def __init__(self, *args, **kwargs):
        ladder_predefined1 = kwargs.pop('ladder', None)
        ladder_predefined2 = kwargs.pop('usuario', None)
        super(LadderInspectionForm, self).__init__(*args, **kwargs)
        if ladder_predefined1:
            self.fields['ladder'].initial = ladder_predefined1
            self.fields['ladder'].disabled = True  # Hace el campo deshabilitado
            self.fields['usuario'].initial = ladder_predefined2
            self.fields['usuario'].disabled = True  # Hace el campo deshabilitado

templates/ladders/status/add.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
    SuipluMX - Adding new status for ladders
{% endblock %}

{% block content %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Ladders</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            {% include "ladders/ladder_toolbar.html" %}
        </div>
    </div>
    <h5>Adding new ladder status</h5>
    <div class="row p-2 mb-0">
        <div class="containervieweqipment">
            <div class="containervieweqipmenthead">
                <div class="row">
                    <div class="col-6">General information</div>
                    <div class="col-6">
                        <div class="text-end">
                        </div>
                    </div>
                </div>
            </div>
            <div class="containervieweqipmentbody">
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{form|crispy}}
                    <div class="pb-2 text-end">
                        <button type="submit" class="btn btn-success">Add</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script src="{% static 'js/forklifts/forklifts.js' %}"></script>
{% endblock %}

templates/ladders/status/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}SuipluMX - Registrated status for ladders{% endblock %}
{% block content %}
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Ladders</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            {% include "ladders/ladder_toolbar.html" %}
        </div>
      </div>
  <div class="row pb-2 px-1">
    <div class="col-6">
      <h5>Registrated ladder status</h5>
    </div>
    <div class="col-6">
      {% if perms.ladders.add_lattersstatus %}
        <div class="text-end">
          <a href="{% url 'ladders_status_add' %}" class="btn btn-dark">
            <img class="filter-white" src="{% static 'images/ico/hdd-stack.svg' %}" /> Add status
          </a>
        </div>
      {% endif %}
    </div>
  </div>
<table class="table">
  <thead>
    <tr>
      <th width="15%" scope="col">Status</th>
      <th width="10%" scope="col">Count</th>
      <th width="25%" scope="col">Percentage</th>
      <th width="40%" scope="col">Scales</th>
      <th width="10%" class="text-end" scope="col">Operations</th>
    </tr>
  </thead>
  <tbody>
        {% for status in status_counts %}
        <tr>
            <td ><span style="height: 18px;width: 18px;background-color:{{ status.color }};border-radius: 50%;vertical-align: sub;display: inline-block;" class="dot"></span> {{ status.name }}</td>
            <td>{{ status.count }} Ladders</td>
            <td><div class="progress m-2">
  <div class="progress-bar
    bg-success
    " role="progressbar" style="width:{% widthratio status.count conteo 100 %}%;" aria-valuenow="{% widthratio status.count conteo 100 %}" aria-valuemin="0" aria-valuemax="100" data-toggle="tooltip" data-placement="top" data-bs-original-title="{% widthratio status.count conteo 100 %} %">
    {% widthratio status.count conteo 100 %} %
  </div>
</div></td>
            <td>
                    
<div class="accordion" id="accordionPanelsStayOpenExample">
  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button collapsed header_fkl_count" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseThree{{status.id}}" aria-expanded="false" aria-controls="panelsStayOpen-collapseThree">
        {{ status.count }} out of {{ conteo }} ladders</button>
    </h2>
    <div id="panelsStayOpen-collapseThree{{status.id}}" class="accordion-collapse collapse">
      <div class="accordion-body">
        {% if status.count %}
        {% for obj in status.objs.all %}
        <a href="{% url 'ladders_view' obj.id %}" type="button" class="btn btn-sm btn-primary"><div class="pb-1"><img  class="filter-white" src="{% static 'images/ico/ladder.svg' %}" /> {{ obj.clave }}</div></a>
        {% endfor %}
        {% else %}
            <a type="button" class="btn btn-sm btn-primary"><div class="pb-1">Nothing to show</div></a>
        {% endif %}
      </div>
    </div>
  </div>
</div>
            </td>
            <td class='text-end align-middle'><a href="{% url 'ladders_status_view' status.id %}" class="btn btn-dark btn-sm">View</a></td>
        </tr>
        {% empty %}
            <td>No status available</td>
        {% endfor %}
</table>
      <script>
const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))
    </script>
<script>
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();
});
</script>
{% endblock %}

templates/ladders/status/view.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    SuipluMX - Viewing {{ data.name }} ladder status
{% endblock %}

{% block content %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Ladders</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            {% include "ladders/ladder_toolbar.html" %}
        </div>
    </div>
    <h5>Viewing ladder status: {{data.name}}</h5>
    <div class="text-end"></div>
    <script src="{% static 'js/functions_forklifts.js' %}"></script>
    <div class="row">
        <div class="col-6 p-2 mb-0">
            <div class="containervieweqipment">
                <div class="containervieweqipmenthead">
                    <div class="row">
                        <div class="col-6">General information</div>
                        <div class="col-6">
                            <div class="text-end">
                                {% if perms.ladders.change_lattersstatus %}
                                <div class="text-end">
                                    <a href="{% url 'ladders_status_edit' data.id %}" name="edit_b" id="edit_b" class="nav-link"><span class="align-text-bottom"><img class="filter-white" src="{% static 'images/ico/pencil-square.svg' %}"></span></a>
                                </div>
                                {% else %}
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="align-middle containervieweqipmentbody">
                    <div class="row">
                        <div class="col-4 fw-bolder">Name</div>
                        <div class="col-8 fw-medium">{{ data.name }}</div>
                    </div>
                    <div class="row">
                        <div class="col-4 fw-bolder">Color</div>
                        <div class="col-8 fw-medium"><span style="height: 18px;width: 18px;background-color:{{ data.color  }};border-radius: 50%;vertical-align: sub;display: inline-block;" class="dot"></span> {{ data.color }}</div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-6 p-2">
            <div class="containervieweqipment">
                <div class="containervieweqipmenthead">
                    <div class="row">
                        <div class="col-6">Ladders count ({{ conteo }} ladders)</div>
                        <div class="col-6">
                        </div>
                    </div>
                </div>
                <div class="containervieweqipmentbody">
                    {%if mas_data %}
                    {% for forklift in mas_data %}
                        <a href="{% url 'ladders_view' forklift.id %}" type="button" class="m-1 btn btn-sm btn-primary"><img  class="filter-white" src="{% static 'images/ico/ladder.svg' %}" /> {{ forklift.clave }}</a>
                    {% endfor %}
                    {% else%}
                        <a type="button" class="btn btn-sm btn-primary"><div class="pb-1">Nothing to show</div></a>
                    {% endif%}
                </div>
            </div>
        </div>
    </div>
            {% if perms.ladders.delete_lattersstatus %}
            <div class="row p-2 mb-0">
            <div class="containerdanger">
                <div class="containerdangerhead">
                    <div class="row">
                        <div class="col-6"><a class="fw-bolder text-reset text-decoration-none">Danger zone</a></div>
                        <div class="col-6">
                            <div class="text-end">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="containerdangerbody">
                    <hr>
                    <div class="row">
                        <div class="col-9 align-middle">
                            <a  class="fw-bolder text-reset text-decoration-none">Delete this status</a><br>
                            <a class="fw-medium text-reset text-decoration-none">Once you delete this status, there is no going back. Please be certain.</a>
                        </div>
                        <div class="col-3 text-end"> <button type="button" onClick='delete_content({{data.id}})' class="btn btn-danger">Delete this status</button></div>
                    </div>
                    <hr>
                </div>
            </div>
    </div>
            {% else %}
            {% endif %}
    <!-- MODAL DELETE -->
  <div class="modal fade" id="modal_delete" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="staticBackdropLabel">Are you sure you want to delete this status?</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">All related items will be deleted. You can't undo this action.
          <form class="eliminar-formulario" method="post" action="{% url 'ladders_status_delete' data.id %}">
            {% csrf_token %}
            <input type="hidden" name="delete_id" id="delete_id" value="{{data.id}}">
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-dark" data-bs-dismiss="modal">Cancel</button>
          <button type="submit" class="btn btn-danger">Delete</button>
        </div>
          </form>
      </div>
    </div>
  </div>

    <script src="{% static 'js/forklifts/status.js' %}"></script>
{% endblock %}